remote_theme: pages-themes/minimal@v0.2.0
theme: jekyll-theme-minimal
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
include:
  - index.md
